name: build-and-push
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
    paths:
      - 'images/**'
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        image:
            - name: python3.11
              docker_tag: latest
              python_version: "3.11"
            - name: python3.11-slim
              docker_tag: 3.11-slim
              python_version: "3.11"
            - name: python3.11-alpine
              docker_tag: 3.11-alpine
              python_version: "3.11"
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
        -
            name: Checkout
            uses: actions/checkout@v3
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v2
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
        -
            name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
            name: Build and push
            uses: docker/build-push-action@v4
            with:
                context: ./images
                file: ./images/${{ matrix.image.name }}.dockerfile
                push: true
                tags: mhadam/hypercorn:${{ (matrix.image.docker_tag == 'latest' && 'latest') || format('{0}-{1}', matrix.image.docker_tag, github.ref_name) }}
