name: build-and-push
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
    paths:
      - 'images/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        -
            name: Checkout
            uses: actions/checkout@v3
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v2
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
        -
            name: Login to DockerHub
            uses: docker/login-action@v2
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
            name: Build and push
            uses: docker/bake-action@v2
            env:
                VERSION: 3.11
                TAG: ""
            with:
                workdir: ${{ github.workspace }}
                push: true
                files: |
                    './images/docker-bake.hcl'